
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARG END GT GTGT LT PATH PIPE SEMICOLONprogram : statementscommand : command ARGcommand : ARGstatement : commandcommand : command PIPE commandcommand : command GT PATH\n    separator : SEMICOLON\n              | END\n              | separator END\n              | separator SEMICOLON\n    \n    statements : statement\n    '
    
_lr_action_items = {'ARG':([0,4,5,6,7,9,10,],[5,6,-3,-2,5,6,-6,]),'$end':([1,2,3,4,5,6,9,10,],[0,-1,-11,-4,-3,-2,-5,-6,]),'PIPE':([4,5,6,9,10,],[7,-3,-2,7,-6,]),'GT':([4,5,6,9,10,],[8,-3,-2,8,-6,]),'PATH':([8,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,],[3,]),'command':([0,7,],[4,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','bash.py',26),
  ('command -> command ARG','command',2,'p_funcname2','bash.py',69),
  ('command -> ARG','command',1,'p_funcname','bash.py',73),
  ('statement -> command','statement',1,'p_statement','bash.py',78),
  ('command -> command PIPE command','command',3,'p_statement_pipe','bash.py',82),
  ('command -> command GT PATH','command',3,'p_statement_redirect_truncate','bash.py',86),
  ('separator -> SEMICOLON','separator',1,'p_separator','bash.py',92),
  ('separator -> END','separator',1,'p_separator','bash.py',93),
  ('separator -> separator END','separator',2,'p_separator','bash.py',94),
  ('separator -> separator SEMICOLON','separator',2,'p_separator','bash.py',95),
  ('statements -> statement','statements',1,'p_statements','bash.py',100),
]
